# UIUC Reboot Capstone Project

## Overview
You work for a regional soft drink distribution center that has access to invoice data from convenience stores (invoices.csv), product data (items.csv), and customer reviews (the files in reviews/).

You would like to examine the data for a few features, then plug them into a recommendation engine to see if you can improve sales.

### Loading Data

In [2]:
import pandas as pd
import glob as glob
import zipfile
import numpy as np               # to get unique values from list using numpy.unique

# Item.csv rundown

In [4]:
item = pd.read_csv('item.csv')
print(item.info())
print()
print(item.columns)
print()
print("Column Names:")
for col in item.columns:
    print(col)
print()
item

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4166 entries, 0 to 4165
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Item_id              4166 non-null   int64
 1   Item_Description     4166 non-null   object
 2   Category             4162 non-null   object
 3   Pack                 4166 non-null   int64
 4   Bottle_Volume_ml     4166 non-null   float64
 5   Bottle_Cost          4166 non-null   float64
 6   Bottle_Retail_Price  4163 non-null   float64
dtypes: float64(3), int64(2), object(2)
memory usage: 228.0+ KB
None

Index(['Item_id', 'Item_Description', 'Category', 'Pack', 'Bottle_Volume_ml',
       'Bottle_Cost', 'Bottle_Retail_Price'],
      dtype='object')

Column Names:
Item_id
Item_Description
Category
Pack
Bottle_Volume_ml
Bottle_Cost
Bottle_Retail_Price

,Item_id,Item_Description,Category,Pack,Bottle_Volume_ml,Bottle_Cost,Bottle_Retail_Price
0,101,Kanna's Grapefruit Soda,Grapefruit Soda,6,750.0,4.32,6.48
1,102,Alphonse's Fruit Punch,Fruit Punch,6,800.0,3.33,5.00
2,103,Yummy Surstromming Juice,NaN,1,750.0,10.30,20.10
3,107,Tamaki's Watermelon Cream,Cream Soda,6,750.0,4.44,6.66
4,108,Kaori's Grapefruit Soda,Grapefruit Soda,6,750.0,3.12,4.68
...,...,...,...,...,...,...,...
4161,994644,Saitama's Cream Soda,Cream Soda,6,750.0,12.60,18.90
4162,994786,Kenji's Vanilla Cream Soda,Cream Soda,6,750.0,4.27,6.41
4163,994972,Tanya's Vanilla Cream Soda,Cream Soda,6,750.0,5.87,8.81
4164,995606,Sakura's Cream Soda,Cream Soda,12,750.0,3.72,5.58
4165,996026,Tetsuya's Cream Soda,Cream Soda,6,750.0,6.81,10.22

In [56]:
# Read in files here

print("Compiling Product Reviews:\t\t", end='')

zf = zipfile.ZipFile('reviews.zip')
datReviews = [filename for filename in zf.namelist() if filename.endswith(".dat")]
print(len(datReviews))

Compiling Product Reviews:		50000

In [3]:
# Basic dataframe info